# Generated by Django 4.1.7 on 2023-03-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MAIN_USER', 'Main User')], default='MAIN_USER', max_length=20),
        ),
    ]
