# Generated by Django 4.1.7 on 2023-03-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['position'], 'verbose_name': 'Question Option', 'verbose_name_plural': 'Question Options'},
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
