version: '3'
services:
  talataa:
    build:
        context: ../
        dockerfile: docker/Dockerfile
    restart: always
    env_file:
        - ./.env
    command: python ./src/manage.py runserver 0.0.0.0:8000
    volumes:
        - ../src:/www/src
    ports:
        - "8000:8000"
    depends_on:
        - talataa_db
  talataa_db:
    image: "postgres:13-alpine"
    restart: unless-stopped
    env_file:
        - ./.env
    ports:
        - "5436:5432"
    volumes:
        - ../postgres/data:/var/lib/postgresql/data
  talataa_test:
    build:
        context: ../
        dockerfile: docker/Dockerfile
    restart: always
    env_file:
        - ./.env
    command: pytest
    volumes:
        - ../src:/www/src
    ports:
        - "8000:8000"
    depends_on:
        - talataa_db