# Generated by Django 4.1.7 on 2023-03-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentquiz',
            options={'verbose_name': 'Student Quiz', 'verbose_name_plural': 'Student Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='studentquizanswer',
            options={'verbose_name': 'StudentQuizAnswer', 'verbose_name_plural': 'StudentQuizAnswers'},
        ),
    ]
